name : getting branch name
on : 
  push :
jobs : 
  getbranchname :
    runs-on : ubuntu-latest
    steps:
    - name: checkout-code 
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/scripts/requirements.txt
    - name: run python script
      run: python ./.github/scripts/py_trial.py
