name: checking reusable workflow
on : 
  pull_request:
  # workflow_dispatch:
    
    
    

jobs:
  jobs-on-workflowcall-matrix:
    strategy:
      matrix:
        env_name: [ apac-stage, emea-stage ]
    uses: ./.github/workflows/s3-template.yml
    with: 
      environment_name: ${{ matrix.env_name }}
      folder_path: DataFolder
  