name: checking reusable workflow
on : 
  # pull_request:
  workflow_dispatch:
    
    
    

jobs:
  apac_stage:
    uses: ./.github/workflows/s3-template.yml
    with: 
      environment_name: apac-stage
      folder_path: DataFolder/apac-stage
  