name : getallchangedfiles
on : 
  pull_request:
    
    
jobs :
  commitjob: 
    runs-on: ubuntu-latest
    steps : 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name : getbranch
      run : echo "branchin=${{ github.head_ref }}" 
    - name : getfoldersunderDataFolder
      run : |
        value=$(git diff origin/master origin/${{ github.head_ref }} --name-only | grep DataFolder/apac-stage/)
        if [[ -n $value ]]
        then 
          echo "trigger_apac=true" >> $GITHUB_ENV
        else
          echo "trigger_apac=false" >> $GITHUB_ENV
        fi

        
        value2=$(git diff origin/master origin/${{ github.head_ref }} --name-only | grep DataFolder/emea-stage/)
        if [[ -n $value2 ]]
        then 
          echo "trigger_emea=true" >> $GITHUB_ENV
        else
          echo "trigger_emea=false" >> $GITHUB_ENV
        fi
    outputs:
      RUN_APAC : ${{ env.trigger_apac }}
      RUN_EMEA : ${{ env.trigger_emea }}

  apacJob:
    needs : commitjob
    if :  needs.commitjob.outputs.RUN_APAC == 'true'
    runs-on: ubuntu-latest
    steps : 
    - name: checktrigger
      run : echo ${{ needs.commitjob.outputs.RUN_APAC }}
  
  emeaJob :
    needs : commitjob
    if : needs.commitjob.outputs.RUN_EMEA == 'true'
    runs-on : ubuntu-latest
    steps :
    - name: checktrigger
      run : echo ${{ needs.commitjob.outputs.RUN_EMEA }}