name : getallchangedfiles
on : 
  push:
    
jobs :
  commitjob: 
    runs-on: ubuntu-latest
    steps : 
    - name : getbranch
      run : echo "branchin=${{ github.ref_name }}" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v3
    - name : getfoldersunderDataFolder
      run : |
        arr=()
        for i in $(ls -d DataFolder/apac-stage/*/); do echo "${i}"; arr+=($i); done
        for value in "${arr[@]}"
        do 
            echo "list_apac=$(git diff master '${steps.getbranch.outputs.branchin}' --name-only | grep $value)" >> $GITHUB_OUTPUT
            echo $list_apac
            # if [[ $list_apac != "" ]]
            # then
            #       echo 
            # fi    
        done
        arr=()
        for i in $(ls -d DataFolder/emea-stage/*/); do arr+=($i); done
        for value in "${arr[@]}"
        do 
            echo "list_emea=$(git diff master ${{ steps.getbranch.outputs.branchin }} --name-only | grep $value)" >> $GITHUB_OUTPUT 
            echo $list_emea
        done
    outputs:
      APAC_LIST : ${{ steps.getfoldersunderDataFolder.outputs.list_apac }}
      EMEA_LIST : ${{ steps.getfoldersunderDataFolder.outputs.list_emea }}
      CURRENT_BRANCH : ${{ steps.getbranch.outputs.branchin }}

  apacJob:
    if :  needs.commitjob.outputs.APAC_LIST != ''
    runs-on: ubuntu-latest
    steps : 
    - name: chekingapaclist
      run : echo "${{ needs.commitjob.outputs.APAC_LIST }}"