name : getallchangedfiles
on : 
  push:
    
jobs :
  commitjob: 
    runs-on: ubuntu-latest
    steps : 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name : getbranch
      run : echo "branchin=${{ github.ref_name }}" 
    - name : getfoldersunderDataFolder
      run : |
        value=$(git diff origin/master HEAD --name-only | grep DataFolder/apac-stage/)
        if [[ -n $value ]]
        then 
          echo "trigger_apac=1" >> $GITHUB_OUTPUT
        else
          echo "trigger_apac=0" >> $GITHUB_OUTPUT
        fi

        echo "trigger_emea=0" >> $GITHUB_OUTPUT
    - name: printoutput
      run : |
        echo ${{ steps.getfoldersunderDataFolder.outputs.trigger_apac }} ${{ steps.getfoldersunderDataFolder.outputs.trigger_emea }}
    outputs:
      RUN_APAC : ${{ steps.getfoldersunderDataFolder.outputs.trigger_apac }}
      RUN_EMEA : ${{ steps.getfoldersunderDataFolder.outputs.trigger_emea }}

  apacJob:
    needs : commitjob
    # if :  needs.commitjob.outputs.RUN_APAC == true
    runs-on: ubuntu-latest
    steps : 
    - name: chekingapaclist
      run : echo ${{ needs.commitjob.outputs.RUN_APAC }}