name : getallchangedfiles
on : 
  push:
    
jobs :
  commitjob: 
    runs-on: ubuntu-latest
    steps : 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name : getbranch
      run : echo "branchin=${{ github.ref_name }}" 
    - name : getfoldersunderDataFolder
      run : |
        value=$(git diff origin/master HEAD --name-only | grep DataFolder/apac-stage/)
        if [[ -n $value ]]
        then 
          echo "trigger_apac=false" >> $GITHUB_ENV
          echo "$trigger_apac"
          echo "say something"
        else
          echo "trigger_apac=true" >> $GITHUB_ENV
          echo "$trigger_apac"
        fi

        echo "trigger_emea=true" >> $GITHUB_ENV
    - name: printoutput
      run : |
        echo ${{ env.trigger_apac }} ${{ env.trigger_emea }}
    outputs:
      RUN_APAC : ${{ env.trigger_apac }}
      RUN_EMEA : ${{ env.trigger_emea }}

  apacJob:
    needs : commitjob
    if :  needs.commitjob.outputs.RUN_APAC == 'true'
    runs-on: ubuntu-latest
    steps : 
    - name: chekingapaclist
      run : echo ${{ needs.commitjob.outputs.RUN_APAC }}