name : getallchangedfiles
on : 
  push:
    
jobs :
  commitjob: 

    runs-on: ubuntu-latest
    steps : 
    - name: Install zsh
      run: sudo apt-get update; sudo apt-get install zsh
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name : getbranch
      run : echo "branchin=${{ github.ref_name }}" 
    - name : getfoldersunderDataFolder
      shell : zsh {0}
      run : |
        # arr=()
        # list_apac=()
        # for i in $(ls -d DataFolder/apac-stage/*/); do echo "${i}"; arr+=($i); done
        # for value in "${arr[@]}"
        # do 
        #     apac_obj=$(git diff origin/master HEAD --name-only | grep $value)
        #     if [[apac_obj != ""]]
        #     then 
              
        # done
        trigger_apac=0
        value=$(git diff origin/master HEAD --name-only | grep DataFolder/apac-stage/)
        echo "$value"
        pwd
        echo "*******************************************"
        echo "$(git diff origin/master HEAD --name-only | grep DataFolder/apac-stage/)" > out_apac.txt
        ls
        if [ -n $value ]
        then 
          trigger_apac=1
        fi
        echo "$trigger_apac" >> $GITHUB_OUTPUT
        rm -f out_apac.txt

        # arr=()
        # for i in $(ls -d DataFolder/emea-stage/*/); do arr+=($i); done
        # for value in "${arr[@]}"
        # do 
        #     echo "list_emea=$(git diff origin/master HEAD --name-only | grep $value)" >> $GITHUB_OUTPUT 
        #     echo $list_emea
        # done


        trigger_emea=0
        # value=$(git diff origin/master HEAD --name-only | grep DataFolder/emea-stage/)
        # if [["$(git diff origin/master HEAD --name-only | grep DataFolder/emea-stage/)" != '']]
        # then 
        #   trigger_emea=1
        # fi
        echo "$trigger_emea" >> $GITHUB_OUTPUT
    outputs:
      RUN_APAC : ${{ steps.getfoldersunderDataFolder.outputs.trigger_apac }}
      RUN_EMEA : ${{ steps.getfoldersunderDataFolder.outputs.trigger_emea }}

  apacJob:
    if :  needs.commitjob.outputs.RUN_APAC == 1
    runs-on: ubuntu-latest
    steps : 
    - name: chekingapaclist
      run : echo "${{ needs.commitjob.outputs.APAC_LIST }}"