name: sync files
on:
  workflow_dispatch:
jobs:
  s3-job:
    environment: stage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: s3 sync
      run: |
        aws s3 sync ./DataFolder s3://testingactionsbucket/syncingFolder --exclude "README.md"
        echo "synced"