name: sync files
on:
  workflow_dispatch:
jobs:
  s3-job:
    environment: stage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.REGION }}

    - name: s3 sync
      run: |
        aws s3 sync ./DataFolder s3://testingactionsbucket/syncingFolder --exclude "README.md" --delete
        echo "synced"
