name : stop ec2 instance workflow
on: 
   workflow_dispatch:
    inputs:
      # region:
      #   description: 'APAC_REGION | EMEA_REGION | SA_REGION'
      #   required: true 
      #   type: string
      # rolename:
      #   description: 'APAC_PROD_ROLE | APAC_STAGE_ROLE | EMEA_STAGE_ROLE | EMEA_PROD_ROLE | SA_STAGE_ROLE | SA_PROD_ROLE'
      #   required: true 
      #   type: string
      ec2_instance_arn : 
        description : enter instance arn
        required : true
        type : string
jobs:
    run-shell-commands:
        runs-on : ubuntu-latest
        steps :
            - name : echo
              run : echo "running "
            - name : cli-version
              run : aws --version
            - name : aws credentials
              uses : aws-actions/configure-aws-credentials@v1
              # env :
              #   role : ${{ inputs.rolename }}
              #   region : ${{ inputs.region }}
              with :
                aws-access-key-id : ${{ secrets.ACCESS_KEY_APAC }}
                aws-secret-access-key : ${{ secrets.SECRET_ACCESS_KEY_APAC }}
                role-to-assume : ${{ secrets.APAC_STAGE_ROLE }}
                aws-region : ${{ secrets.APAC_REGION }}
            - name : stop ec2 instance
              run : aws ec2 stop-instances --instance-ids ${{ inputs.ec2_instance_arn }}
            


    