name : shell-commands
on: 
   workflow_dispatch:
    inputs:
      requirement:
        description: 'Test scenario tags'
        required: true 
        type: string
jobs:
    run-shell-commands:
        runs-on : ubuntu-latest
        steps :
            - name : echo
              run : echo running ${{ inputs.requirement }}
            - name : cli-version
              run : aws --version

    