name : shell-commands
on: [push]
jobs:
    run-shell-commands:
        runs-on : ubuntu-latest
        steps :
            - name : echo
              run : echo "running"
            - name : cli-version
              run : aws --version

    