name : workflowcallreusable
on : 
   workflow_call:
     inputs:
        environment_name: 
          required: true
          type: string

jobs:
  triggerenv: 
    runs-on: ubuntu-latest
    steps : 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name : getenv
      run : echo ${{ inputs.environment_name }}
    